# Generated by Django 5.0.1 on 2024-03-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user_type',
            field=models.CharField(default='Patient', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='user_type',
            field=models.CharField(default='Patient', max_length=100),
        ),
    ]
